import { ThemeProvider } from "@/components/theme/theme-provider";
import { AuthProvider } from "./_contexts/authcontext";
import "./globals.css";

export const metadata = {
  title: "Coordina",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
