import type { Metadata } from "next";
import "./globals.css";
import Providers from "./provider";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { AuthProvider } from "./_contexts/authcontext";
import { AgencyAuthProvider } from "./_contexts/agencyauthContext";
import ConvexClientProviders from "@/providers/ConvexClientProviders";

export const metadata: Metadata = {
  title: "Coordina",
  description: "Generated by create next app",
};

// const convex = new ConvexReactClient(process.env.VITE_CONVEX_URL as string);

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className="antialiased">
        <ConvexClientProviders>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AgencyAuthProvider>
              <AuthProvider>
                <Providers>{children}</Providers>
              </AuthProvider>
            </AgencyAuthProvider>
          </ThemeProvider>
        </ConvexClientProviders>
      </body>
    </html>
  );
}